[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

fs_permissions = [
  { access = "read-write", path = "./" },
]

[profile.compiler]
evm_version="paris"

[profile.production]
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 79
multiline_func_header = "params_first"
ignore = [
  "lib/**/*.sol",
  "**/dependencies/**/*.sol"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config