name: Slither analysis
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: contracts
    steps:
      - uses: actions/checkout@v3

      - name: Run slither analyzer
        uses: crytic/slither-action@v0.3.0
        with:
          target: 'src/v2/'
          solc-version: 0.8.21
